eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true  #使用ip注册到注册中心
server:
  port: 9001
spring:
  application:
    name: AIGOU_ZUUL
zuul:
  routes:
    aigou_plat: /login/**
  ignored-services: "*" #过滤所有
  prefix: /aigou #前缀
