server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到注册中心
spring:
  application:
    name: AIGOU_PLAT